pipelines:
  - name: calculate_ci_job
    steps: 
      - name: build_app
        type: MvnBuild
        configuration:
          integrations:
            - name: pipelines_creds_for_calculate
            - name: tals_artifactory_integration
          sourceLocation: .
          autoPublishBuildInfo: false
          mvnCommand: clean install -s settings.xml -Dusername=${int_pipelines_creds_for_calculate_username} -Dpassword=${int_pipelines_creds_for_calculate_password}
          configFileLocation: .
          configFileName: config.file.yml
          inputResources:
            - name: calculate_repository_resource
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info               

      - name: xray_scan
        type: XrayScan
        configuration:
          inputSteps:
            - name: publish_app_build
          inputResources:
            - name: appl_build_info
              trigger: false

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          inputSteps:
            - name: xray_scan
          targetRepository: libs-release-prod
          integrations:
            - name: tals_artifactory_integration
          inputResources:
            - name: appl_build_info
          outputResources:
            - name: appl_promoted_build_info    
            
            
      - name: create_release_bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: calculate-application-rb
          releaseBundleVersion: 1.0
          dryRun: false
          sign: true
          inputResources:
            - name: appl_build_info
            - name: calculate-application-rb-query.aql
          inputSteps:
            - name: promote_app_build
          outputResources:
            - name: appl_release_bundle_resource
