pipelines:
  - name: calculate_ci_job
    steps: 
      - name: build_app
        type: MvnBuild
        configuration:
          integrations:
            - name: pipelines_creds_for_calculate
            - name: tals_artifactory_integration
          sourceLocation: .
          mvnCommand: clean deploy -s settings.xml -Dusername=${int_pipelines_creds_for_calculate_username} -Dpassword=${int_pipelines_creds_for_calculate_password}
          configFileLocation: .
          configFileName: config.file.yml
          inputResources:
            - name: calculate_repository_resource
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version


      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info               


      - name: xray_scan
        type: XrayScan
        configuration:
          inputResources:
            - name: appl_build_info
              trigger: false


     - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: calculate_demo
          integrations:
            - name: tals_artifactory_integration
          inputResources:
            - name: appl_build_info
          outputResources:
            - name: appl_promoted_build_info              