pipelines:
  - name: calculate_ci_job
    steps: 
      - name: build_app
        type: MvnBuild
        configuration:
          integrations:
            - name: myCredentials
          sourceLocation: .
          mvnCommand: clean install -s settings.xml -Dusername=int_myCredentials_username -Dpassword=int_myCredentials_password
          configFileLocation: .
          configFileName: config.file.yml
          inputResources:
            - name: calculate_repository_resource
          integrations:
            - name: tals_artifactory_integration
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info               
